name: Build LaTeX

on: push

jobs:
  build-pdf:
    name: Build PDF
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Install
        run: sudo apt-get install texlive texlive-xetex texlive-lang-european texlive-science texlive-fonts-recommended language-pack-sv
      - name: Build
        run: make koncept.pdf
