name: Test build KonCEPT

on: push

jobs:
  build-pdf:
    name: 'Build book'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [koncept.pdf, koncept-tryck.pdf]
    steps:
      - name: 'Check out'
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            **/*.aux
            **/*.idx
          key: ${{ runner.os }}-${{ matrix.variant }}
      - name: Install
        run: sudo apt-get install texlive texlive-xetex texlive-lang-european texlive-science texlive-fonts-recommended texlive-fonts-extra language-pack-sv
      - name: Build
        run: make ${{ matrix.variant }}
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: koncept-pdf
          path: '*.pdf'
          retention-days: 14
